version: 2
jobs:
  test_node_10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

  test_node_12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

  prettier:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run prettier:check

  release:
    docker:
      - image: circleci/node:10
    environment:
      GIT_AUTHOR_EMAIL: evan@evanchiu.com
      GIT_AUTHOR_NAME: Evbot 🤖🚀
      GIT_COMMITTER_EMAIL: evan@evanchiu.com
      GIT_COMMITTER_NAME: Evbot 🤖🚀
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test_node_10
      - test_node_12
      - prettier
      - release:
          requires:
            - test_node_10
            - test_node_12
            - prettier
